 version: "3"

 services:
   redis:
     image: redis:latest
     ports:
       - "6379:6379"
   db:
     image: postgres:latest
     ports:
       - "5432:5432"
     volumes:
       - postgres-data:/var/lib/postgresql/data-latest
     environment:
       - POSTGRES_PASSWORD=
       - POSTGRES_USER=${USER}

 # create local volume for postgres data to persist (ie through computer restarts)
 volumes:
   postgres-data:
     driver: local
